version: '3'

services: 
  web:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./src:/usr/share/nginx/html
      - ./latihan:/usr/share/nginx/latihan
      - ./about:/usr/share/nginx/about
      - ./dashboard:/usr/share/nginx/dashboard
      - ./belajar:/usr/share/nginx/belajar
    restart: always